export const routePairs: Record<string, string> = {
  "/":                              "/es/",
  "/es/":                           "/",
  "/about":                         "/es/nosotros",
  "/es/nosotros":                   "/about",
  "/services":                      "/es/servicios",
  "/es/servicios":                  "/services",
  "/services/field-rental":         "/es/servicios/canchas",
  "/es/servicios/canchas":          "/services/field-rental",
  "/services/leagues":              "/es/ligas",
  "/es/ligas":                      "/services/leagues",
  "/services/pickup":               "/es/partido-libre",
  "/es/partido-libre":              "/services/pickup",
  "/services/birthday-parties":     "/es/fiestas",
  "/es/fiestas":                    "/services/birthday-parties",
  "/services/camps":                "/es/campamentos",
  "/es/campamentos":                "/services/camps",
  "/services/training":             "/es/entrenamiento",
  "/es/entrenamiento":              "/services/training",
  "/blog":                          "/es/blog",
  "/es/blog":                       "/blog",
  "/contact":                       "/es/contacto",
  "/es/contacto":                   "/contact",
};